# Generated by Django 3.0.5 on 2020-04-20 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(blank=True, default='https://i.stack.imgur.com/l60Hf.png', max_length=255, null=True, upload_to='images/%Y/%m/%d/'),
        ),
    ]
