# Generated by Django 3.0.5 on 2020-05-02 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='city',
            field=models.CharField(default='San Diego', max_length=20),
        ),
    ]
