# Generated by Django 3.0.5 on 2020-04-19 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='age',
            field=models.CharField(choices=[('1', '16-18'), ('2', '19-21'), ('3', '22-25'), ('4', '26-30'), ('5', '30+')], default='1', max_length=5),
        ),
        migrations.AddField(
            model_name='match',
            name='type',
            field=models.CharField(choices=[('SC', 'Soccer'), ('BK', 'Basketball'), ('BS', 'Baseball')], default='SC', max_length=15),
        ),
    ]
