# Generated by Django 3.0.6 on 2020-05-09 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_match_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='city',
            field=models.CharField(default='San Diego', max_length=100),
        ),
    ]
