# Generated by Django 3.0.5 on 2020-04-19 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200419_1508'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='lat',
            field=models.FloatField(default=32.8801),
        ),
        migrations.AddField(
            model_name='match',
            name='lon',
            field=models.FloatField(default=-117.2361),
        ),
    ]
