# Generated by Django 3.0.5 on 2020-04-19 08:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20200419_1519'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='maxPlayers',
            field=models.IntegerField(default=11),
        ),
        migrations.AddField(
            model_name='match',
            name='time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
