# Generated by Django 3.0.6 on 2020-05-13 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20200509_1940'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='host_id',
            field=models.CharField(default='', max_length=30),
        ),
    ]
