# Generated by Django 3.0.5 on 2020-04-19 08:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0005_match_roster'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='roster',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
