# Generated by Django 3.0.5 on 2020-04-19 09:35

import api.randomizer
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20200419_1555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='id',
            field=models.CharField(default=api.randomizer.pkgen, max_length=8, primary_key=True, serialize=False),
        ),
    ]
