# Generated by Django 3.0.6 on 2020-05-13 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_remove_match_host_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='host_id',
            field=models.IntegerField(default=0),
        ),
    ]
