# Generated by Django 3.0.6 on 2020-05-13 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_match_host_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='host_id',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
