# Generated by Django 3.0.6 on 2020-05-13 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20200513_1442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='host_id',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
