# Generated by Django 3.0.6 on 2020-05-15 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_match_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='description',
            field=models.TextField(max_length=500),
        ),
    ]
