# Generated by Django 3.0.6 on 2020-05-18 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_auto_20200515_1217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='images/%Y/%m/%d/'),
        ),
    ]
