# Generated by Django 3.0.6 on 2020-05-31 07:01

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_auto_20200518_0220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='type',
            field=models.CharField(choices=[('SC', 'Soccer'), ('BK', 'Basketball'), ('BS', 'Baseball'), ('FB', 'Football'), ('VB', 'Volleyball')], default='SC', max_length=15),
        ),
        migrations.AlterField(
            model_name='profile',
            name='sports',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('SC', 'Soccer'), ('BK', 'Basketball'), ('BS', 'Baseball'), ('FB', 'Football'), ('VB', 'Volleyball')], default='SC', max_length=14),
        ),
    ]
