# Generated by Django 3.0.6 on 2020-05-31 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_auto_20200531_0701'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='zip_code',
        ),
        migrations.AddField(
            model_name='profile',
            name='lat',
            field=models.FloatField(default=32.8801),
        ),
        migrations.AddField(
            model_name='profile',
            name='lon',
            field=models.FloatField(default=-117.2361),
        ),
    ]
