# Generated by Django 3.0.6 on 2020-06-01 14:31

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_auto_20200531_0758'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='maxSkill',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='minSkill',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='skill',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(default=0), default=list, size=None),
        ),
        migrations.AlterField(
            model_name='match',
            name='description',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='match',
            name='maxPlayers',
            field=models.IntegerField(default=11, null=True),
        ),
    ]
